- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: command
    ansible.builtin.command: dnf install nginx