- name: creating instances
  hosts: local
  connection: local
  vars:
    subnetid: subnet-0d8a0eef049b5fb05
    sg: sg-0fbc2d03237543962
    ami: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
  tasks: 
  - name: creating instances ec-2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpn_subnet_id: "{{ subnetid }}"
      instance_type: t3.micro
      security_group: "{{ sg }}"
      image_id: "{{ ami }}"
      register: ec2-instance
    loop: "{{ instances }}"

  - name: printing the output
    ansible.builtin.debug:
      msg: "{{ ec2-instance }}"
