- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0d8a0eef049b5fb05 # replace with your susubnet-0d8a0eef049b5fb05bnet id
    sg_id: "sg-0fbc2d03237543962"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: ganeshsiripuram.tech
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: yes
    loop: "{{ ec2_instances.results }}" 

  - name: create r53 public records
    amazon.aws.route53:
      state: present 
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0],public_ip_address }}"
      wait: true
      overwrite: yes
    loop: "{{ec2_instances.results }}"
    when: item.item==frontend