- name: demo on filters or functions
  hosts: local
  connection: local
  tasks:
  - name: task1 filters
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }}"

  - name: task2 filters
    vars: 
      greeting: "Hello World"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"