- name: demo on filters or functions
  hosts: local
  connection: local
  tasks:
  - name: task1 filters
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }}"

  - name: task2 filters
    vars: 
      greeting: "Hello World"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: task3 filters
    vars:
      greeting: "balaji 777"
    ansible.builtin.debug:
      msg: "{{ greeting | upper}}"

  - name: task4 filters
    vars:
      numbers: [1,2,3,5,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: task5 filters
    vars:
      numbers: [4,5,1,9,6]
    ansible.builtin.debug:
      msg: "MIN: {{ numbers | min }}  MAX: {{ numbers | max}}"

  - name: task6 filters
    vars:
      course:
        name: "AWS"
        duration: 120hrs
        trainer: "Navin"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: task 7 filters
    vars:
      course:
      - { "key": "name" ,"value": "AWS" }
      - { "key": "duration", "value": "120hrs"}
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

  - name: task 8 filters
    vars:
      myip: "172.157.1.1"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4}}"
