- name: demo on filters or functions
  hosts: local
  connection: local
  tasks:
  - name: task1 filters
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }}"

  - name: task2 filters
    vars: 
      greeting: "Hello World"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: task3 filters
    vars:
      greeting: "balaji 777"
    ansible.builtin.debug:
      msg: "{{ greeting | upper}}"

  - name: task4 filters
    vars:
      numbers: [1,2,3,5,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"