- name: installing packages
  hosts: web
  become: yes
  tasks: 
  - name: task 1 installing packages
    ansible.builtin.package:
      name: {{ item }}
      state: present
    loop: 
    - mysql
    - nginx
    - httpd
    - postfix
