- name: multi task variable
  hosts: web
  vars:
   COURSE: devops with aws
   duration: 120hrs
   trainer: shivakumar
  tasks:
  - name: task 1 variable e
    ansible.builtin.debug:
     msg: "I am learing {{COURSE}} ,duration is {{duration}},trainer is {{trainer}}"

  - name: task 2 variable
    vars: 
     COURSE: ansible
    ansible.builtin.debug:
     msg: "Ganesh is learning {{COURSE}} ,duration is {{duration}} ,trainer is {{trainer}}"