- name: sample yaml
  hosts: local
  vars:
    tools:
      cm: ansible
      ci: terraform
      cloud: aws
  tasks:
    name: task1 
    ansible.builtin.debug:
      msg: "tools are {{ item }}"
    loops: "{{tools}}"